apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints: # [1]
    - web
  routes: # [2]
    - kind: Rule
      match: Host(`localhost`) && PathPrefix(`/argocd`) # [3]
      priority: 10 # [4]
      services: # [8]
        - kind: Service
          name: argocd-server
          namespace: argocd
          passHostHeader: true
          port: 80 # [9]
          scheme: http
          weight: 10
